<?php
    /** @var Resolve_Resolve_Block_Payment_Redirect $this **/
    $order = Mage::getSingleton('checkout/session')->getQuote();
    $paymentMethod = $order->getPayment()->getMethodInstance();
?>
<html>
    <body>
        <script type="text/javascript" src="<?= Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)?>frontend/base/default/js/resolve/resolve.js"></script>
        <div class="notice-label">Please wait, we are collecting order data</div>
        <div class="lds-grid"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
        <style>
          .notice-label {
              font-size: 33px;
              color: rgb(29, 65, 104);
              font-family: "Proxima Nova";
              text-align: center;
              font-weight: 900;
              font-family: monospace;
              margin-top: 260px;
              margin-bottom: 80px;}
              
          .lds-grid {
              display: inline-block;
              width: 64px;
              height: 64px;
              position: absolute;
              left: 0;
              right: 0;
              margin: 0 auto;
          }
          .lds-grid div {
            position: absolute;
            width: 13px;
            height: 13px;
            border-radius: 50%;
            background: #03A9F4;
            animation: lds-grid 1.2s linear infinite;
          }
          .lds-grid div:nth-child(1) {
            top: 6px;
            left: 6px;
            animation-delay: 0s;
          }
          .lds-grid div:nth-child(2) {
            top: 6px;
            left: 26px;
            animation-delay: -0.4s;
          }
          .lds-grid div:nth-child(3) {
            top: 6px;
            left: 45px;
            animation-delay: -0.8s;
          }
          .lds-grid div:nth-child(4) {
            top: 26px;
            left: 6px;
            animation-delay: -0.4s;
          }
          .lds-grid div:nth-child(5) {
            top: 26px;
            left: 26px;
            animation-delay: -0.8s;
          }
          .lds-grid div:nth-child(6) {
            top: 26px;
            left: 45px;
            animation-delay: -1.2s;
          }
          .lds-grid div:nth-child(7) {
            top: 45px;
            left: 6px;
            animation-delay: -0.8s;
          }
          .lds-grid div:nth-child(8) {
            top: 45px;
            left: 26px;
            animation-delay: -1.2s;
          }
          .lds-grid div:nth-child(9) {
            top: 45px;
            left: 45px;
            animation-delay: -1.6s;
          }
          @keyframes lds-grid {
            0%, 100% {
              opacity: 1;
            }
            50% {
              opacity: 0.5;
            }
          }
        </style>
        <script type="text/javascript">
            window.resolve.checkout(<?php echo json_encode($paymentMethod->getCheckoutObject($order))?>);
        </script>
    </body>
</html>