<?php
/** @var Resolve_Resolve_Block_Payment_Form $this **/
?>
<?php
    $helper = Mage::helper('resolve');

?>
<style type="text/css">
    .resolve-module-version {
        display: none;
    }

    .resolve_payment_info {
        color: #6f6f6f;
        font-size: 14px;
    }
</style>
<ul class="form-list resolve" id="payment_form_resolve" style="display:none;">
    <li class="form-alt">
            <div class="resolve_payment_info">
                <?php if ($helper->isPlainDescriptionTextEnabled()): ?>
                    <?= $helper->getDescriptionHtmlAfter();?>
                <?php else: ?>
                    <p><?php echo $this->__('You will be redirected to Resolve to securely complete your purchase. Just fill out a few pieces of basic information and get a real-time decision. Checking your eligibility won\'t affect your credit score.'); ?></p>
                <?php endif; ?>
            </div>
    </li>
</ul>
<span class="resolve-module-version"><?php echo $this->helper('resolve')->getModuleConfigVersion(); ?></span>
